### ISSUE TITLE
Checklist

### ISSUE THREAD

**Issue by skiadas** [gitslaton/HARIS#1]
You can call someone's attention on an issue by using their github handle @gitslaton @enmiller94 @abraddy24 

These are not all equally difficult:
- [x] Read about [Git-flavored Markdown](https://help.github.com/categories/writing-on-github/).
- [x] Create a `README.md` file, populate with basic information about your language.
- [x] Copy over basic interpreter files from assignments project: `driver.ml`, `lexer.mll`, `parser.mly`, `types.ml`, `types.mli`.
- [x] Create a `.gitignore` file modelled after the corresponding file in assignments project. Ask if you are not sure what this does.
- [x] Write some example programs in your language, starting with very simple programs and progressing to more complex ones. This will help you decide how to make your surface language. As a simple example, you could make let statements look like: `with (x = 5) { ... }`. You will need to decide how your language should look like. Writing a couple of simple programs is a good way to start thinking about that.
- [x] Start a `semantics.md` file that will describe the specific syntax and semantics of the features in the language. You don't have to put everything in at once, this may start almost empty.
- [x] Start a `details.md` file that will describe problems you encountered and how you dealt with them. Again, this may start largely empty. You should add information there _as you encounter problems_.
- [x] Create a `tests.ml` file that is meant to run with `types.ml` and `types.mli` for automated tests.
- [x] Update the `README.md` with links to other important files.
- [x] Add support for numbers in the language (not any operations yet, just numbers).
- [x] Make sure the language at this point compiles and runs.
- [x] Add parsing/interpretation for arithmetic operations
- [x] Add parsing/interpretation for boolean literals and conditional
- [x] Set up a type for your language types and a "typecheck" function in the types file
- [x] Implement typechecking for the constructs in the language so far, test it via the `tests.ml` file.
- [x] Implement comparison operators and logical operators.
- [x] Add equality operator, and use a separate function that tests when two values are equal to do so. You will need to update this function as you add new kinds of values. You will need to decide what values can equal what other values (e.g. should two closures ever be equal?).
- [x] Create a function that produces a string representation of a type as you want it printed out to the user. Same for values.
- [x] Change the driver so that it does typechecking before it interprets, and so it prints both a value and a type when it prints the results.
- [x] Add values and types for tuples.
- [x] Add parsing/interpretation for tuples. You will have to decide how to access the parts of a tuple (e.g. if `t` is `(1, 4, 5)` then `t.2` or `t#2` might return `4`?).
- [x] Add let statements and variables. You need to decide what the allowed variables in your language are.
- [x] Add functions as a language construct. You will need to add a type for function argument, and one for function return.
- [x] Add parsing for functions. This will necessitate making your parser read types.
- [x] Add lists as a language construct. You will need:
  - [x] A new value
  - [x] A new type
  - [x] A new construct for putting an element in the front of a list
  - [x] A new construct for the empty list
  - [x] A new construct for testing if a list is null
  - [x] A new construct for getting the head of the list and one for getting the tail.
- [ ] Write `map`, `filter` and `foldr` and/or `foldl` in your language.
- [x] Implement top-level "let"s. The bindings they create must be in effect for the rest of the interaction.
- [x] Polish the semantics file. For instance, did you list the keywords that are reserved and can't be used as variables?
- [ ] Write and test longer programs in your language.
- [x] Polish all markdown files and submission files.

Extensions that you should try:
- [ ] A Racket-like `cond`
- [ ] Make sure a function closure only stores the part of the environment that has the values it will need, instead of the whole current environment (in other words it should include only variables that appear "free" in the function body).
